config/routes.rb
Rails.application.routes.draw do

	resources :usuarios, as: :users, only: [:show, :update]
	resources :friendships, only:[:create, :update, :index]
    resources :posts do
        resources :comments
    end

 # = //
 # /**/
 #get -> /posts
 #get -> /new
 #post -> /create
 #get -> /edit/:id
 #put -> /update
 #get -> /show/:idss


	post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"

	authenticated :user do
		root 'main#home'
	end

	unauthenticated :user do
		root 'main#unregistered'
	end

	devise_for :users, controllers:{
		omniauth_callbacks: "users/omniauth_callbacks"
	}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	mount ActionCable.server => '/cable'
end

app/views/partials/_nav.haml
%header.mdl-layout__header.mdl-layout__header--scroll
  .mdl-layout__header-row
    %span.mdl-layout-title= link_to "SocialCo", root_path, class: 'white-text no-margin no-decoration'
    .mdl-layout-spacer
    %nav.mdl-navigation
      -if user_signed_in?
        =link_to 'Mis amigos', friendships_path(), class: 'white-text right-space'
        =link_to 'cerrar sesion', destroy_user_session_path, method: :delete, class: "white-text"
.mdl-layout__drawer
  %span.mdl-layout-title SocialCo
  %nav.mdl-navigation
    =link_to "Inicio", root_path, class: 'mdl-navigation__link'
    =link_to "Mi perfil", current_user, class: 'mdl-navigation__link'
    =link_to "Mis amigos", friendships_path, class: 'mdl-navigation__link'